### ISSUE TITLE
【HELP】About Recent Updates

### ISSUE THREAD

**Issue by Si-JiX** [TerakomariGandesblood/kepub#17]
It seems that the authorities have begun to ban the account
Is there any solution？

**Comment by TerakomariGandesblood** [comment]
In about half a month, I will have some time to start rewriting the project and solve this problem.

**Comment by Si-JiX** [comment]
Thank you.
By the way, there is a reminder that you may not be able to use. When I was testing, I found that the interface on the web side was dead (I don't know much about the interface between C++and the mobile side, so I can't help it)

**Comment by TerakomariGandesblood** [comment]
Because I'm busy, I haven't paid attention to this project for a long time, and it can no longer be used as expected. I believe that it will become a useful tool again after rewriting in the near future. In addition, I plan to write a desktop program (or web, not yet determined). Looking forward to your feedback.

**Comment by Si-JiX** [comment]
I see. Thank you again for your efforts
